/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shenron-dragon-ball-96e8ad1e206941ce859c5733bec75d30
Title: Shenron (Dragon Ball)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Dragon2(props) {
  const { nodes, materials } = useGLTF('/assets/shenron_dragon_ball.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="ShenronFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group
                name="Shenron"
                position={[-5.58712196, 5.53750849, 2.4e-7]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Shenron_Green_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Shenron_Green_0.geometry}
                  material={materials.Green}
                />
                <mesh
                  name="Shenron_Yellow_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Shenron_Yellow_0.geometry}
                  material={materials.Yellow}
                />
                <mesh
                  name="Shenron_09_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Shenron_09_-_Default_0'].geometry}
                  material={materials['09_-_Default']}
                />
                <mesh
                  name="Shenron_08_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Shenron_08_-_Default_0'].geometry}
                  material={materials['08_-_Default']}
                />
              </group>
              <group
                name="One_Star"
                position={[2.81213856, 6e-8, -0.39202452]}
                rotation={[-Math.PI / 3, 0, 0]}
                scale={0.04821515}>
                <group name="Object_9" position={[-0.00000677, -0.00000586, 0.00000338]}>
                  <mesh
                    name="One_Star_02_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['One_Star_02_-_Default_0'].geometry}
                    material={materials['02_-_Default']}
                  />
                  <mesh
                    name="One_Star_03_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['One_Star_03_-_Default_0'].geometry}
                    material={materials['03_-_Default']}
                  />
                </group>
              </group>
              <group
                name="Four_Star"
                position={[11.78864384, 6e-8, 13.47361279]}
                rotation={[-Math.PI / 3, 0, 0]}
                scale={0.04821515}>
                <group name="Object_13" position={[-194.57307434, 249.7824707, -144.21202087]}>
                  <mesh
                    name="Four_Star_02_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Four_Star_02_-_Default_0'].geometry}
                    material={materials['02_-_Default']}
                  />
                  <mesh
                    name="Four_Star_03_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Four_Star_03_-_Default_0'].geometry}
                    material={materials['03_-_Default']}
                  />
                </group>
              </group>
              <group
                name="Two_Star"
                position={[-4.4274559, 0.00000103, 13.21439457]}
                rotation={[-Math.PI / 3, 0, 0]}
                scale={0.04821515}>
                <group name="Object_17" position={[141.754776, 245.12646484, -141.52391052]}>
                  <mesh
                    name="Two_Star_02_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Two_Star_02_-_Default_0'].geometry}
                    material={materials['02_-_Default']}
                  />
                  <mesh
                    name="Two_Star_03_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Two_Star_03_-_Default_0'].geometry}
                    material={materials['03_-_Default']}
                  />
                </group>
              </group>
              <group
                name="Five_Star"
                position={[-11.51535892, 6e-8, -0.54888785]}
                rotation={[-Math.PI / 3, 0, 0]}
                scale={0.04821515}>
                <group name="Object_21" position={[288.76043701, -2.08524132, 1.203915]}>
                  <mesh
                    name="Five_Star_02_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Five_Star_02_-_Default_0'].geometry}
                    material={materials['02_-_Default']}
                  />
                  <mesh
                    name="Five_Star_03_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Five_Star_03_-_Default_0'].geometry}
                    material={materials['03_-_Default']}
                  />
                </group>
              </group>
              <group
                name="Seven_Star"
                position={[-5.81789398, 6e-8, -14.25766087]}
                rotation={[-Math.PI / 3, 0, 0]}
                scale={0.04821515}>
                <group name="Object_25" position={[170.5929718, -248.31785583, 143.36642456]}>
                  <mesh
                    name="Seven_Star_02_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Seven_Star_02_-_Default_0'].geometry}
                    material={materials['02_-_Default']}
                  />
                  <mesh
                    name="Seven_Star_03_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Seven_Star_03_-_Default_0'].geometry}
                    material={materials['03_-_Default']}
                  />
                </group>
              </group>
              <group
                name="Star_Three"
                position={[11.54647446, -2.7e-7, -13.88551903]}
                rotation={[-Math.PI / 3, 0, 0]}
                scale={0.04821515}>
                <group name="Object_29" position={[-189.55038452, -241.63354492, 139.50724792]}>
                  <mesh
                    name="Star_Three_02_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Star_Three_02_-_Default_0'].geometry}
                    material={materials['02_-_Default']}
                  />
                  <mesh
                    name="Star_Three_03_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Star_Three_03_-_Default_0'].geometry}
                    material={materials['03_-_Default']}
                  />
                </group>
              </group>
              <group
                name="Six_Star"
                position={[17.13963318, 6e-8, -0.60476255]}
                rotation={[-Math.PI / 3, 0, 0]}
                scale={0.04821515}>
                <group name="Object_33" position={[-305.55459595, -3.08884478, 1.78334606]}>
                  <mesh
                    name="Six_Star_02_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Six_Star_02_-_Default_0'].geometry}
                    material={materials['02_-_Default']}
                  />
                  <mesh
                    name="Six_Star_03_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Six_Star_03_-_Default_0'].geometry}
                    material={materials['03_-_Default']}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/shenron_dragon_ball.glb')
