/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fairy.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF,TransformControls } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
export default function Fairy(props) {
  const { nodes, materials } = useGLTF('/assets/fairy.glb')

  
  const fairyRef=useRef()
 
  // useFrame((state,delta)=>{
  //   fairyRef.current.rotation.z+=delta
  // })
  return (
    <>
    <group {...props} dispose={null}>
      <mesh ref={fairyRef} geometry={nodes.Object_2.geometry} material={materials.fb_abWishFairy} rotation={[-Math.PI / 2, 0, -1.065]} scale={11.787} />
    </group>
    <TransformControls object={fairyRef} />
    </>
  )
}

useGLTF.preload('/assets/fairy.glb')
