/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shenron_dragon_ball.glb 
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shenron-dragon-ball-96e8ad1e206941ce859c5733bec75d30
Title: Shenron (Dragon Ball)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Dragon(props) {
  const { nodes, materials } = useGLTF('./assets/shenron_dragon_ball.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-5.587, 5.538, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Shenron_Green_0.geometry} material={materials.Green} />
        <mesh geometry={nodes.Shenron_Yellow_0.geometry} material={materials.Yellow} />
        <mesh geometry={nodes['Shenron_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
        <mesh geometry={nodes['Shenron_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
      </group>
      <group position={[2.812, 0, -0.392]} rotation={[-Math.PI / 3, 0, 0]} scale={0.048}>
        <mesh geometry={nodes['One_Star_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
        <mesh geometry={nodes['One_Star_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
      </group>
      <group position={[11.789, 0, 13.474]} rotation={[-Math.PI / 3, 0, 0]} scale={0.048}>
        <group position={[-194.573, 249.782, -144.212]}>
          <mesh geometry={nodes['Four_Star_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['Four_Star_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
        </group>
      </group>
      <group position={[-4.427, 0, 13.214]} rotation={[-Math.PI / 3, 0, 0]} scale={0.048}>
        <group position={[141.755, 245.126, -141.524]}>
          <mesh geometry={nodes['Two_Star_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['Two_Star_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
        </group>
      </group>
      <group position={[-11.515, 0, -0.549]} rotation={[-Math.PI / 3, 0, 0]} scale={0.048}>
        <group position={[288.76, -2.085, 1.204]}>
          <mesh geometry={nodes['Five_Star_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['Five_Star_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
        </group>
      </group>
      <group position={[-5.818, 0, -14.258]} rotation={[-Math.PI / 3, 0, 0]} scale={0.048}>
        <group position={[170.593, -248.318, 143.366]}>
          <mesh geometry={nodes['Seven_Star_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['Seven_Star_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
        </group>
      </group>
      <group position={[11.546, 0, -13.886]} rotation={[-Math.PI / 3, 0, 0]} scale={0.048}>
        <group position={[-189.55, -241.634, 139.507]}>
          <mesh geometry={nodes['Star_Three_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['Star_Three_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
        </group>
      </group>
      <group position={[17.14, 0, -0.605]} rotation={[-Math.PI / 3, 0, 0]} scale={0.048}>
        <group position={[-305.555, -3.089, 1.783]}>
          <mesh geometry={nodes['Six_Star_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['Six_Star_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./assets/shenron_dragon_ball.glb')
