/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 羊咩咩 (https://sketchfab.com/minisheep0.0)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/ply-20180201-t-1d42364558e341f79d7776b04c965c39
Title: Ply 20180201_t
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useControls } from 'leva'


export default function WhiteFairy(props) {
 const model=useGLTF('/assets/white_fairy.glb')
 const animations=useAnimations(model.animations,model.scene)
 //console.log(animations.names)
//console.log(animations)
//  const {animationName}=useControls('Fairy Controls',{
//     animationName:{options:animations.names}
//  })
  const {animationName}=useControls('FairyControls',{
    animationName:{options:{
      
      NoNo: 'anm_02000019',
       Greet: 'anm_02000020',
       Pray: 'anm_02000034',
       Stop: 'anm_02000021'}
    }
  })

  useEffect(()=>{
    const actionNoNo=animations.actions.anm_02000019
    const actionStop=animations.actions.anm_02000021
    const actionPray=animations.actions.anm_02000034
    const actionGreet=animations.actions.anm_02000020

    const generalAnimation=animations.actions[animationName]
    generalAnimation.reset().fadeIn(0.5).play()

    /***********************************************/
    // window.setTimeout(()=>{
    //  actionStop.play()
    //   actionStop.crossFadeFrom(actionNoNo,1)
    // },2000)
    // window.setTimeout(()=>{
    //  actionPray.play()
    //   actionPray.crossFadeFrom(actionStop,2)
    // },5000)
    /*******************************************************/
      return()=>{
        generalAnimation.fadeOut(0.5)
      }

  },[animationName])
 return <primitive object={model.scene } {...props}></primitive>
}

useGLTF.preload('/assets/white_fairy.glb')
